[build]
  publish = "."
  command = ""

# 🩵 This fixes the /admin redirect loop issue
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

# 🩵 Keep this for SPA-style routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
